name: Deploy Project 12A- Gatsby Contentful Blogsite
env:
  owner: SharjeelSafdar
  repo: project12a-gatsby-contentful-blog

# Controls when the action will run. Triggers the workflow on
# 1) push event for master branch
# 2) repository_dispatch event from a remote server,
#    in our case from Contentful webhook.
on:
  push:
    branch: [master]
  repository_dispatch:

jobs:
  # This workflow builds the react app on a Ubuntu VM and deploys it to surge.
  DeployApp:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with: { node-version: "14.15.0" }

      - name: Install Dependencies
        uses: jaid/action-npm-install@v1.2.1

      - name: Run Type Checking and Build Gatsby App
        run: npm run build
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

      - name: Install Surge
        run: npm i -g surge

      - name: Deploy to Surge
        run: surge ./public https://gatsby-contentful-blog-p12a.surge.sh --token ${{ secrets.SURGE_TOKEN }}
