name: Deploy Project 12A- Gatsby Contentful Blogsite

# Controls when the action will run. Triggers the workflow on push event
# but only for the master branch
on:
  push:
    branch: [master]

jobs:
  # This workflow builds the react app on a Ubuntu VM and deploys it to surge.
  DeployApp:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: Production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check the Repository
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with: { node-version: "14.15.0" }

      - name: Install Dependencies
        uses: jaid/action-npm-install@v1.2.1

      - name: Run Type Checking and Build Gatsby App
        run: npm run build

      - name: Install Surge
        run: npm i -g surge

      - name: Deploy to Surge
        run: surge ./public --token ${{ secrets.SURGE_TOKEN }}
